export function getSkillMdContent(): string {
  const lines = [
    '---',
    'name: code-atlas-navigator',
    'description: Use this skill when you need to explore, understand, or search this codebase. Input a file or directory path relative to the project root to retrieve the path to its detailed natural language summary. Use this progressively to navigate from the root directory down to specific target files without reading the full raw source code.',
    '---',
    '',
    '# Codebase Navigation Guide',
    '',
    'This repository has been pre-analyzed and summarized into natural language Markdown files. To save context window and improve accuracy, **do not read the raw source code directly**. Instead, use this skill to progressively navigate the repository layer by layer.',
    '',
    '## 🧭 How to Explore the Codebase',
    '',
    "1. **Start High-Level**: If you don't know the exact file location, begin by querying the summary of the root directory (`.`).",
    '2. **Progressive Disclosure**: Read the directory summary to understand its sub-components. Identify the next relevant sub-directory or file based on your current task.',
    '3. **Drill Down**: Query the summaries of those specific sub-components. Repeat this until you locate the target function, class, or logic.',
    '',
    '## 🛠️ How to Locate a Summary File',
    '',
    'Use the provided Python script to map the original codebase path to its corresponding Markdown summary path.',
    '',
    '**Script Specification:**',
    '* **Input Parameter**: The relative path of the target file or directory with respect to the project root.',
    '* **Output**: The relative path of the Markdown summary file with respect to the project root.',
    '* **Fallback**: If the summary Markdown file cannot be found, the script will strictly output `N/A`.',
    '',
    '### Execution Commands',
    '',
    'Since the execution environment may vary, please use the appropriate command based on your current operating system:',
    '',
    '**For Linux / macOS (Bash/Zsh):**',
    '```bash',
    'python3 scripts/get_summary.py <relative/path/to/target>',
    '```',
    '(Note: If python3 is not found, fallback to python).',
    '',
    '**For Windows (CMD/PowerShell):**',
    '```dos',
    'python scripts\\get_summary.py <relative\\path\\to\\target>',
    '```',
    '(Note: You may also use py or python3 depending on the Windows environment setup).',
  ]

  return lines.join('\n') + '\n'
}